---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas-util
    component: app-orch-svr
  name: app-orch-svr-external
  namespace: "openfaas-util"
spec:
  type: ClusterIP
  ports:
    - port: 7443
      protocol: TCP
      targetPort: 7443
  selector:
    app: app-orch-svr
