---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: openfaas-util
    component: kong
  name: kong
  namespace: "openfaas-util"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name:  kong
        image: pcloud.edgescale.org/pcloud/kong
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /home
          name: kong-volume
        ports:
        - containerPort: 8443
          hostPort: 8443
        - containerPort: 8000
          hostPort: 8000
      volumes:
      - name: kong-volume
        hostPath: 
          path: /etc/edgescale/kong
      imagePullSecrets:
        - name: kube-repos
