---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas-util
    component: kong
  name: kong-external
  namespace: "openfaas-util"
spec:
  type: ClusterIP
  ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: kong

