---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas-util
    component: mft
  name: mft-external
  namespace: "openfaas-util"
spec:
  type: ClusterIP
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: mft

