---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas-util
    component: minio
  name: minio-external
  namespace: "openfaas-util"
spec:
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio

