---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas-util
    component: minio-api 
  name: minio-api-external
  namespace: "openfaas-util"
spec:
  type: ClusterIP
  ports:
    - port: 10086
      protocol: TCP
      targetPort: 10086
  selector:
    app: minio-api 

