---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas-util
    component: b-est
  name: b-est-external
  namespace: "openfaas-util"
spec:
  type: ClusterIP
  ports:
    - port: 11443
      protocol: TCP
      targetPort: 443
  selector:
    app: b-est

