---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas-util
    component: haproxy
  name: haproxy-external
  namespace: "openfaas-util"
spec:
  type: ClusterIP
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: haproxy

