---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: openfaas-util
    component: named
  name: named
  namespace: "openfaas-util"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: named
    spec:
      hostNetwork: true
      containers:
      - name:  named
        image: resystit/bind9
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/bind/named.conf
          name: named-volume
        - mountPath: /var/bind/pri/edgescale.zone
          name: edgescalezone-volume
      volumes:
      - name: named-volume
        hostPath:
          path: /etc/edgescale/etc/named/named.conf
      - name: edgescalezone-volume
        hostPath:
          path: /etc/edgescale/etc/named/edgescale.zone

