---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas-util
    component: nginx
  name: nginx-external
  namespace: "openfaas-util"
spec:
  type: ClusterIP
  ports:
    - port: 12443
      protocol: TCP
      targetPort: 443
  selector:
    app: nginx

