---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas-util
    component: postgres
  name: postgres-external
  namespace: "openfaas-util"
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
