---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfaas-util
    component: redis
  name: redis-external
  namespace: "openfaas-util"
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
  selector:
    app: redis
