---
  
es_api: https://api.edgescale.org/v1
es_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjQ3MjI1NzI1OTIsInVpZCI6NDgsInVzZXJuYW1lIjoiYjI1MzMyIiwiYWRtaW4iOjEsImFjY291bnRfdHlwZV9pZCI6Mn0.ceX6O-Lo7u3zGCT8qCLTunOk9js4qpDbECTePM_ERgk 
addr: :443
certfile: /etc/est/est.crt
keyfile: /etc/est/est.key
trustcafile: /etc/est/trustca.crt
default_days: 365

rootca:
  certfile: /etc/est/ca/RootCA.crt
  keyfile: /etc/est/ca/RootCA.key

ocsp_server:
  - https://int.e-est.edgescale.org/.well-known/ocsp

